### ISSUE TITLE
Why py.test vs nose

### ISSUE THREAD

**Issue by rufuspollock** [okfn/coding-standards#13]
Happy with either!

Just wondering for my own information why py.test rather nose.

**Comment by roll** [comment]
I suppose nowadays pytest is just superior with modular fixture system, failed assertion reporting etc Also for now I guess it could be considered as as a standard way in py community (with tox).

The best source of information here could be @vitorbaptista

**Comment by pwalsh** [comment]
Python community has moved in droves to py.test for these type of reasons. 

Also @rgrp the setup we have now with tox, thanks to @vitorbaptista , is really great. We'll also be extending our guidelines soon with his latest advancements ;) https://github.com/vitorbaptista/pyconuk_helloworld/blob/master/tox.ini

**Comment by roll** [comment]
Starter repo just in case https://github.com/okfn/oki-py

**Comment by rufuspollock** [comment]
FIXED.
