### ISSUE TITLE
Git branching

### ISSUE THREAD

**Issue by pwalsh** [okfn/coding-standards#2]
Not sure how established the conventions are, but following all/most of Git Flow has been very helpful for me over the last years:

http://nvie.com/posts/a-successful-git-branching-model/

Your model here is already somewhat based on parts of it anyway.

Another good thing about git flow is that some tools have helpers for it built in (e.g.: [SourceTree](http://www.sourcetreeapp.com) which is a hg/git client for Mac and Windows) as well as the "official" commonly used git extensions: https://github.com/nvie/gitflow

**Comment by brew** [comment]
I think being at least familiar with gitflow is useful, and following it in spirit. Not always necessary for very small projects perhaps.

**Comment by pwalsh** [comment]
FIXED.
