### ISSUE TITLE
Use tox for running tests

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/coding-standards#4]
It provides a standard way of running the tests (just run `tox`), and also allows running tests on multiple python versions.

There are some issues on configuring tox + travis-ci, but they're easy to solve. The problem is that they both have their own build matrix infrastructure, so we have to write a small workaround. For an example on how to do it, check https://github.com/okfn/datapackage-py/blob/master/tox.ini and https://github.com/okfn/datapackage-py/blob/master/.travis.yml

**Comment by pwalsh** [comment]
@vitorbaptista great. I've not used tox, but it sounds like a good flow... PR?

**Comment by pwalsh** [comment]
@vitorbaptista would love for you to do this :). I want to standardise all our projects around your method of using tox.

**Comment by pwalsh** [comment]
cc @akariv

**Comment by vitorbaptista** [comment]
Sure! I've added it to my backlog, and will work on it soon :+1:

**Comment by pwalsh** [comment]
FIXED. The text just says use tox. the real meat will be the accompanying lib that demonstrates.
