### ISSUE TITLE
Use eslint instead of jscs

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/coding-standards#5]
The advantage of eslint is that it not only checks for coding style, but also potential bugs like unused variables, accidental globals, and others. I think it very useful.

For a more through comparison, check http://www.sitepoint.com/comparison-javascript-linting-tools/ and https://davidwalsh.name/eslint. Google also switched from jscs to eslint on their javascript boilerplate repository a few months ago (discussion at https://github.com/google/web-starter-kit/issues/747).

The JavaScript ecosystem is crazy, with new frameworks and libraries appearing every week. We shouldn't try to keep up with it, but I think there's a clear advantage on moving away from jscs here.

**Comment by pwalsh** [comment]
Ok! +1.

**Comment by pwalsh** [comment]
FIXED.
