### ISSUE TITLE
Rebase + Squash commits before merge from feature branch to master

### ISSUE THREAD

**Issue by akariv** [okfn/coding-standards#7]
Do we want to enforce it? 
1. I think it's better to have one commit per fix in the master branch, which is easier to revert if necessary and reduces clutter (and rebase pains) for others.
2. It allows the master branch to have no merge commits, which tend to be a real pain.

**Comment by akariv** [comment]
related resource: [rebaseandsqua.sh](http://rebaseandsqua.sh/)

**Comment by pwalsh** [comment]
I think it is better as a rule, but it requires more discipline (which again, probably a good thing):
1. If people backup lots of changes in a feature branch, then squashing it all into one commit is not helpful.
2. I personally have been quite lazy with rebase (ie: I barely ever do it) so it feels inauthentic to dictate to the team.

Who has thoughts on this @amercader @brew @vitorbaptista @roll @kravets-levko @borysyuk @nigelbabu @kiote

I'm +1 and we all just commit to doing it, but want to hear from others.

**Comment by akariv** [comment]
Just a thought (based on what we did in EverythingMe) - 
It's not too hard to automate this, so that at the end of a travis build, if everything passed then it will automatically rebase, squash and push a new branch (with a '/squashed' suffix) which will be 'ready to merge'

**Comment by pwalsh** [comment]
@akariv ok, in the case of automation via travis, this then creates a new PR, or can we actually automate the merge too?

**Comment by akariv** [comment]
If we want to automate the merge then it's just a push to git to master
branch (no need for a PR then).
I think that usually we'd want a dev to do the merge, but that can be
configured.

**Comment by kiote** [comment]
I'm not really strong with `rebase -i`, so I usually do `merge --squash` and then PR of that squashed branch. Not sure how you guys usually do that. 

But if I realize that my commit way too big for review I make a two different, with logic separated manually. I suspect that is what `rebase` actually for, but... This works for a small team of developers I'm currently in also.

There we do actual code review though, so if the only purpose is to revert changes quickly – then it's okay to have one big commit with everything in it. If you also have a purpose to review the code, then possibly `rebase` is more helpful.

**Comment by pwalsh** [comment]
@akariv let's leave this open, but I'm -1 on suggesting that everyone rebase, for now. Let's come back to this in the next 1-2 months.

**Comment by akariv** [comment]
:+1:

**Comment by roll** [comment]
It could be a per-project rule. 

For mature widely-used packages it could be great and bad for other stuff.

**Comment by roll** [comment]
For a reference - https://github.com/blog/2141-squash-your-commits

**Comment by roll** [comment]
I use github button `Squash and Merge` for `OpenTrials` for now. Also tried to `tabulator` etc - https://github.com/frictionlessdata/tabulator-py/commits/master

Without `merge` commit it looks very nice and could be easily reverted.

@akariv @pwalsh 
I suppose we could add something like recommendation (or mention as possible option for maintainer) to use GitHub button to `coding-standards` and close this issue.

**Comment by pwalsh** [comment]
I'm using it too on the data quality repos. I'm 👍 on it.

**Comment by vitorbaptista** [comment]
I agree to add it as a recommendation. I've used it a few times, but not
always. It depends on the pull request. If it contains clean commits with
good messages, I use the usual merge; if not, I squash.
